image: python:3.6

stages:
  - test
  - deploy

test:
  stage: test
  script: echo "No tests at the moment :("

deploy-staging:
  stage: deploy
  before_script:
    - eval $(ssh-agent -s)
    - echo "$STAGING_SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
  script:
    - echo "Deploying on `hostname -i`"
    - python3 -m venv .venv
    - source .venv/bin/activate
    - pip install -r requirements.txt
    - ./scripts/restart.sh
  tags:
    - deploy-staging
