version: "2.1"

services:
  db:
    image: postgres:9.6
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: "drp-dev"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 2s
      timeout: 5s
      retries: 5
  web:
    build: ./Dockerfile.dev
    ports:
      - 8000:8000
    environment:
      FLASK_ENV: development
      DATABASE_URI: "postgresql://postgres:drp-dev@db:5432/postgres"
    volumes:
      - .:/app
    working_dir: /app
    entrypoint: flask run --host 0.0.0.0 --port 8000
    depends_on:
      db:
        condition: service_healthy
