"""Use IDs for superseding guidelines

Revision ID: 18c0ec526634
Revises: ef30b513ba8d
Create Date: 2020-06-14 19:03:58.998306

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '18c0ec526634'
down_revision = 'ef30b513ba8d'
branch_labels = None
depends_on = None


def upgrade():
    # Added manually
    op.execute('create sequence post_id_seq')
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('is_current', sa.Boolean(), nullable=True))
    op.add_column('posts', sa.Column('post_id', sa.Integer(), server_default=sa.text("nextval('post_id_seq')"), nullable=True))
    op.drop_constraint('posts_superseding_id_fkey', 'posts', type_='foreignkey')
    op.drop_column('posts', 'superseding_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('superseding_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('posts_superseding_id_fkey', 'posts', 'posts', ['superseding_id'], ['id'])
    op.drop_column('posts', 'post_id')
    op.drop_column('posts', 'is_current')
    # ### end Alembic commands ###
    ### Added manually
    op.execute('drop sequence post_id_seq')
