"""Add support for guidelines

Revision ID: 55da4590bacd
Revises: e3ab0da0b604
Create Date: 2020-06-09 21:58:11.522716

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '55da4590bacd'
down_revision = 'e3ab0da0b604'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('is_guideline', sa.Boolean(), nullable=True))
    op.add_column('posts', sa.Column('superseding_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'posts', 'posts', ['superseding_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'posts', type_='foreignkey')
    op.drop_column('posts', 'superseding_id')
    op.drop_column('posts', 'is_guideline')
    # ### end Alembic commands ###
