"""Add user id to devices

Revision ID: 63246e4d9192
Revises: a16b28dc3466
Create Date: 2020-06-18 10:08:20.522199

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '63246e4d9192'
down_revision = 'a16b28dc3466'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('devices', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key('devices_user_id_fkey', 'devices', 'users', [
                          'user_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('devices_user_id_fkey', 'devices', type_='foreignkey')
    op.drop_column('devices', 'user_id')
    # ### end Alembic commands ###
