"""Make expo push token unique

Revision ID: 6ef505b5a30c
Revises: 3eebf78b8acf
Create Date: 2020-06-05 21:04:41.226590

"""
from alembic import op
# import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6ef505b5a30c'
down_revision = '3eebf78b8acf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'devices', ['expo_push_token'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'devices', type_='unique')
    # ### end Alembic commands ###
