"""Add index for consistency checking

Revision ID: 70f28165c046
Revises: 18c0ec526634
Create Date: 2020-06-14 20:33:24.333075

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '70f28165c046'
down_revision = '18c0ec526634'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('unique_current_post_id', 'posts', ['post_id', 'is_current'], unique=True, postgresql_where=sa.text('is_current'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('unique_current_post_id', table_name='posts')
    # ### end Alembic commands ###
