"""Add questions table

Revision ID: 7ac801eafaa6
Revises: 359ca2cf281a
Create Date: 2020-06-01 18:42:35.708323

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7ac801eafaa6'
down_revision = '359ca2cf281a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sites',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('name', sa.Text(), nullable=False),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('name')
                    )
    op.create_table('subjects',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('name', sa.Text(), nullable=False),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('name')
                    )
    op.create_table('questions',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('site_id', sa.Integer(), nullable=True),
                    sa.Column('grade', sa.Enum('CONSULTANT', 'SPR',
                                               'CORE_TRAINEE', 'FY2', 'FY1',
                                               'FIY1', name='grade'),
                              nullable=True),
                    sa.Column('specialty', sa.Text(), nullable=True),
                    sa.Column('subject_id', sa.Integer(), nullable=True),
                    sa.Column('text', sa.Text(), nullable=True),
                    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ),
                    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('questions')
    op.drop_table('subjects')
    op.drop_table('sites')
    # ### end Alembic commands ###
