"""Link to relevant post from resolved questions

Revision ID: a16b28dc3466
Revises: b936807b20cf
Create Date: 2020-06-17 21:56:53.052092

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a16b28dc3466'
down_revision = 'b936807b20cf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('questions', sa.Column('post_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'questions', 'posts', ['post_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'questions', type_='foreignkey')
    op.drop_column('questions', 'post_id')
    # ### end Alembic commands ###
