"""Add created_at field to Post

Revision ID: b3542f9fae38
Revises: 8fa1281b9ff8
Create Date: 2020-05-28 14:57:37.299038

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b3542f9fae38'
down_revision = '8fa1281b9ff8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('created_at', sa.DateTime(),
                                    server_default=sa.text('now()'),
                                    nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'created_at')
    # ### end Alembic commands ###
