"""Add views and votes fields to posts

Revision ID: bb7e38062aec
Revises: d2052ef33ef0
Create Date: 2020-06-04 20:57:25.620021

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bb7e38062aec'
down_revision = 'd2052ef33ef0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('views', sa.Integer(), server_default='0', nullable=False))
    op.add_column('posts', sa.Column('votes', sa.Integer(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'votes')
    op.drop_column('posts', 'views')
    # ### end Alembic commands ###
