"""Add resolved field to question

Revision ID: e3ab0da0b604
Revises: 6ef505b5a30c
Create Date: 2020-06-07 09:57:51.177947

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e3ab0da0b604'
down_revision = '6ef505b5a30c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('questions',
                  sa.Column('resolved', sa.Boolean(),
                            server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('questions', 'resolved')
    # ### end Alembic commands ###
