"""Add users table

Revision ID: e5f26fad6af1
Revises: 359ca2cf281a
Create Date: 2020-05-31 16:39:04.611364

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e5f26fad6af1'
down_revision = '359ca2cf281a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('username', sa.String(
                        length=80), nullable=False),
                    sa.Column('first_name', sa.String(
                        length=80), nullable=True),
                    sa.Column('last_name', sa.String(
                        length=80), nullable=True),
                    sa.Column('password_hash', sa.Text(), nullable=False),
                    sa.Column('role',
                              sa.Enum('NORMAL', 'ADMIN', name='userrole'),
                              nullable=False),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('username')
                    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    # ### end Alembic commands ###
