"""Use IDs to track guideline revisions

Revision ID: fc2597055c79
Revises: b70448119cda
Create Date: 2020-06-15 16:36:29.262291

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fc2597055c79'
down_revision = 'b70448119cda'
branch_labels = None
depends_on = None


def upgrade():
    # MANUALLY ADDED
    op.execute('create sequence post_id_seq')
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('is_current', sa.Boolean(), nullable=True))
    op.add_column('posts', sa.Column('post_id', sa.Integer(), server_default=sa.text("nextval('post_id_seq')"), nullable=True))
    op.create_index('unique_current_post_id', 'posts', ['post_id', 'is_current'], unique=True, postgresql_where=sa.text('is_current'))
    op.drop_constraint('posts_superseding_id_fkey', 'posts', type_='foreignkey')
    op.drop_column('posts', 'superseding_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('superseding_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('posts_superseding_id_fkey', 'posts', 'posts', ['superseding_id'], ['id'])
    op.drop_index('unique_current_post_id', table_name='posts')
    op.drop_column('posts', 'post_id')
    op.drop_column('posts', 'is_current')
    # ### end Alembic commands ###
    # MANUALLY ADDED
    op.execute('drop sequence post_id_seq')
