name: CI

on:
  - push
  - pull_request

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout git repo
        uses: actions/checkout@v2

      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: "3.6"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run linter
        run: flake8 drp/

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout git repo
        uses: actions/checkout@v2

      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: "3.6"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: echo "No tests at the moment :("

  deploy:
    runs-on: ubuntu-latest
    needs:
      - check
      - test
    if: success() && github.event_name == 'push' && github.ref == 'refs/heads/master'
    steps:
      - name: Checkout git repo
        uses: actions/checkout@v2

      - name: Publish docker image
        uses: docker/build-push-action@v1
        with:
          repository: hasali19/drp-server
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          tags: latest
          tag_with_sha: true
